services:


  ### 🔹 Angular (serveur de dev sur port 4200)
  angular:
    build: .
    container_name: angular_front
    ports:
      - "80:80"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
    external: true


