services:


  ### 🔹 Angular (serveur de dev sur port 4200)
  angular:
    image: jobmounchili/todo-app-frontend:${BUILD_ENV}
    ports:
      - "80:80"
    networks:
      - app_network
    environment:
    - NODE_ENV=${BUILD_ENV}

networks:
  app_network:
    driver: bridge
    external: true


